//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmbeddedBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedBrowserControlRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedBrowserControlRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmbeddedBrowser.EmbeddedBrowserControlRes", typeof(EmbeddedBrowserControlRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium: {0}.
        /// </summary>
        internal static string Chromium___0 {
            get {
                return ResourceManager.GetString("Chromium___0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium: {0}, CEF: {1}, CefSharp: {2}.
        /// </summary>
        internal static string Chromium___0___CEF___1___CefSharp___2_ {
            get {
                return ResourceManager.GetString("Chromium___0___CEF___1___CefSharp___2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DevTools.
        /// </summary>
        internal static string Close_DevTools {
            get {
                return ResourceManager.GetString("Close_DevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy image location to clipboard.
        /// </summary>
        internal static string Copy_image_location_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_image_location_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Source copied to clipboard.
        /// </summary>
        internal static string HTML_Source_copied_to_clipboard {
            get {
                return ResourceManager.GetString("HTML_Source_copied_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Link In New Tab.
        /// </summary>
        internal static string Open_Link_In_New_Tab {
            get {
                return ResourceManager.GetString("Open_Link_In_New_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf documents (.pdf)|*.pdf.
        /// </summary>
        internal static string Pdf_documents___pdf____pdf {
            get {
                return ResourceManager.GetString("Pdf_documents___pdf____pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf was saved to .
        /// </summary>
        internal static string Pdf_was_saved_to_ {
            get {
                return ResourceManager.GetString("Pdf_was_saved_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse image search tools.
        /// </summary>
        internal static string Reverse_image_search_tools {
            get {
                return ResourceManager.GetString("Reverse_image_search_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse image search using Google.
        /// </summary>
        internal static string Reverse_image_search_using_Google {
            get {
                return ResourceManager.GetString("Reverse_image_search_using_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse image search using TinEye.
        /// </summary>
        internal static string Reverse_image_search_using_TinEye {
            get {
                return ResourceManager.GetString("Reverse_image_search_using_TinEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse image search using Yandex.
        /// </summary>
        internal static string Reverse_image_search_using_Yandex {
            get {
                return ResourceManager.GetString("Reverse_image_search_using_Yandex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected text.
        /// </summary>
        internal static string Save_selected_text {
            get {
                return ResourceManager.GetString("Save_selected_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search selected text using Google.
        /// </summary>
        internal static string Search_selected_text_using_Google {
            get {
                return ResourceManager.GetString("Search_selected_text_using_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show DevTools.
        /// </summary>
        internal static string Show_DevTools {
            get {
                return ResourceManager.GetString("Show_DevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save Pdf, check you have write permissions to .
        /// </summary>
        internal static string Unable_to_save_Pdf__check_you_have_write_permissions_to_ {
            get {
                return ResourceManager.GetString("Unable_to_save_Pdf__check_you_have_write_permissions_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View source.
        /// </summary>
        internal static string View_source {
            get {
                return ResourceManager.GetString("View_source", resourceCulture);
            }
        }
    }
}
