//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionext {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VpnSelectorLibRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VpnSelectorLibRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionext.VpnSelectorLibRes", typeof(VpnSelectorLibRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (created).
        /// </summary>
        public static string @__created_ {
            get {
                return ResourceManager.GetString("__created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        ///Press OK to close it and connect to selected VPN server..
        /// </summary>
        public static string @__Press_OK_to_close_it_and_connect_to_selected_VPN_server_ {
            get {
                return ResourceManager.GetString("__Press_OK_to_close_it_and_connect_to_selected_VPN_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Server: .
        /// </summary>
        public static string _Server__ {
            get {
                return ResourceManager.GetString("_Server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection has disconnected successfully .
        /// </summary>
        public static string A_connection_has_disconnected_successfully_ {
            get {
                return ResourceManager.GetString("A_connection_has_disconnected_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection has successfully connected .
        /// </summary>
        public static string A_connection_has_successfully_connected_ {
            get {
                return ResourceManager.GetString("A_connection_has_successfully_connected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Connection list.
        /// </summary>
        public static string Active_Connection_list {
            get {
                return ResourceManager.GetString("Active_Connection_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active VPN connection found.
        ///        /// .
        /// </summary>
        public static string Active_VPN_connection_found____ {
            get {
                return ResourceManager.GetString("Active_VPN_connection_found____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All User Phonebook path: .
        /// </summary>
        public static string All_User_Phonebook_path__ {
            get {
                return ResourceManager.GetString("All_User_Phonebook_path__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string Application_settings {
            get {
                return ResourceManager.GetString("Application_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN provider.
        /// </summary>
        public static string BaseProxyProvider {
            get {
                return ResourceManager.GetString("BaseProxyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string BaseProxyProvider_Attachments {
            get {
                return ResourceManager.GetString("BaseProxyProvider_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string BaseProxyProvider_Info {
            get {
                return ResourceManager.GetString("BaseProxyProvider_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string BaseProxyProvider_JProxyProviderId {
            get {
                return ResourceManager.GetString("BaseProxyProvider_JProxyProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BaseProxyProvider_Login {
            get {
                return ResourceManager.GetString("BaseProxyProvider_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BaseProxyProvider_Name {
            get {
                return ResourceManager.GetString("BaseProxyProvider_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string BaseProxyProvider_Password {
            get {
                return ResourceManager.GetString("BaseProxyProvider_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security level.
        /// </summary>
        public static string BaseProxyProvider_SecLevel {
            get {
                return ResourceManager.GetString("BaseProxyProvider_SecLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string BaseProxyProvider_URL {
            get {
                return ResourceManager.GetString("BaseProxyProvider_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Preshared Key.
        /// </summary>
        public static string BaseProxyProvider_UserPresharedKey {
            get {
                return ResourceManager.GetString("BaseProxyProvider_UserPresharedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN login.
        /// </summary>
        public static string BaseProxyProvider_VPNLogin {
            get {
                return ResourceManager.GetString("BaseProxyProvider_VPNLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN password.
        /// </summary>
        public static string BaseProxyProvider_VPNPassword {
            get {
                return ResourceManager.GetString("BaseProxyProvider_VPNPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN server.
        /// </summary>
        public static string BaseProxyServer {
            get {
                return ResourceManager.GetString("BaseProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available protocols.
        /// </summary>
        public static string BaseProxyServer_AvailableProtocols {
            get {
                return ResourceManager.GetString("BaseProxyServer_AvailableProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Type.
        /// </summary>
        public static string BaseProxyServer_EncryptionType {
            get {
                return ResourceManager.GetString("BaseProxyServer_EncryptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connections count.
        /// </summary>
        public static string BaseProxyServer_ErrorCount {
            get {
                return ResourceManager.GetString("BaseProxyServer_ErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string BaseProxyServer_Favorite {
            get {
                return ResourceManager.GetString("BaseProxyServer_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string BaseProxyServer_IsArchive {
            get {
                return ResourceManager.GetString("BaseProxyServer_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string BaseProxyServer_JCountry {
            get {
                return ResourceManager.GetString("BaseProxyServer_JCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country(declared).
        /// </summary>
        public static string BaseProxyServer_JCountryDeclared {
            get {
                return ResourceManager.GetString("BaseProxyServer_JCountryDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string BaseProxyServer_JProxyServerId {
            get {
                return ResourceManager.GetString("BaseProxyServer_JProxyServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last error connection date.
        /// </summary>
        public static string BaseProxyServer_LastErrorDate {
            get {
                return ResourceManager.GetString("BaseProxyServer_LastErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last success connection date.
        /// </summary>
        public static string BaseProxyServer_LastSuccessDate {
            get {
                return ResourceManager.GetString("BaseProxyServer_LastSuccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage of testing job.
        /// </summary>
        public static string BaseProxyServer_Stage {
            get {
                return ResourceManager.GetString("BaseProxyServer_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success connections count.
        /// </summary>
        public static string BaseProxyServer_SuccessCount {
            get {
                return ResourceManager.GetString("BaseProxyServer_SuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string BaseProxyServer_Town {
            get {
                return ResourceManager.GetString("BaseProxyServer_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town (declared).
        /// </summary>
        public static string BaseProxyServer_TownDeclared {
            get {
                return ResourceManager.GetString("BaseProxyServer_TownDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string BaseProxyServer_Url {
            get {
                return ResourceManager.GetString("BaseProxyServer_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to VPN server.
        /// </summary>
        public static string Connect_to_VPN_server {
            get {
                return ResourceManager.GetString("Connect_to_VPN_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection: .
        /// </summary>
        public static string Connection__ {
            get {
                return ResourceManager.GetString("Connection__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create VPN entry .
        /// </summary>
        public static string Create_VPN_entry_ {
            get {
                return ResourceManager.GetString("Create_VPN_entry_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deafault connection.
        /// </summary>
        public static string Deafault_connection {
            get {
                return ResourceManager.GetString("Deafault_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all VPN entries.
        /// </summary>
        public static string Delete_all_VPN_entries {
            get {
                return ResourceManager.GetString("Delete_all_VPN_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete VPN entries? Press &quot;Yes&quot; to delete..
        /// </summary>
        public static string Delete_VPN_entries__Press__Yes__to_delete_ {
            get {
                return ResourceManager.GetString("Delete_VPN_entries__Press__Yes__to_delete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect from active VPN connection.
        /// </summary>
        public static string Disconnect_from_active_VPN_connection {
            get {
                return ResourceManager.GetString("Disconnect_from_active_VPN_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disonnect from VPN server .
        /// </summary>
        public static string Disonnect_from_VPN_server_ {
            get {
                return ResourceManager.GetString("Disonnect_from_VPN_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click on this icon creates VPN connection to default VPN server which not set. No connection created..
        /// </summary>
        public static string Double_click_on_this_icon_creates_VPN_connection_to_default_VPN_server_which_not_set__No_connection_created_ {
            get {
                return ResourceManager.GetString("Double_click_on_this_icon_creates_VPN_connection_to_default_VPN_server_which_not_" +
                        "set__No_connection_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Get IP.
        /// </summary>
        public static string Error_Get_IP {
            get {
                return ResourceManager.GetString("Error_Get_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorit connections.
        /// </summary>
        public static string Favorit_connections {
            get {
                return ResourceManager.GetString("Favorit_connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN provider.
        /// </summary>
        public static string FProxyProvider_JProxyProvider {
            get {
                return ResourceManager.GetString("FProxyProvider_JProxyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import VPN servers from vpngate.net.
        /// </summary>
        public static string Import_VPN_servers_from_vpngate_net {
            get {
                return ResourceManager.GetString("Import_VPN_servers_from_vpngate_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: .
        /// </summary>
        public static string IP__ {
            get {
                return ResourceManager.GetString("IP__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Name__ {
            get {
                return ResourceManager.GetString("Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap network_off {
            get {
                object obj = ResourceManager.GetObject("network_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap network_on {
            get {
                object obj = ResourceManager.GetObject("network_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non PPTP no L2TP protocols available for this vpn entry.
        /// </summary>
        public static string Non_PPTP_no_L2TP_protocols_available_for_this_vpn_entry {
            get {
                return ResourceManager.GetString("Non_PPTP_no_L2TP_protocols_available_for_this_vpn_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect to current VPN server when connection lost.
        /// </summary>
        public static string Reconnect_to_current_VPN_server_when_connection_lost {
            get {
                return ResourceManager.GetString("Reconnect_to_current_VPN_server_when_connection_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect to VPN.
        /// </summary>
        public static string Reconnect_to_VPN {
            get {
                return ResourceManager.GetString("Reconnect_to_VPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap red {
            get {
                object obj = ResourceManager.GetObject("red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run application in windows system tray (next run).
        /// </summary>
        public static string Run_application_in_windows_system_tray__next_run_ {
            get {
                return ResourceManager.GetString("Run_application_in_windows_system_tray__next_run_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test.
        /// </summary>
        public static string Run_test {
            get {
                return ResourceManager.GetString("Run_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test for all VPN servers.
        /// </summary>
        public static string Run_test_for_all_VPN_servers {
            get {
                return ResourceManager.GetString("Run_test_for_all_VPN_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test for favorite VPN servers.
        /// </summary>
        public static string Run_test_for_favorite_VPN_servers {
            get {
                return ResourceManager.GetString("Run_test_for_favorite_VPN_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test for selected VPN servers.
        /// </summary>
        public static string Run_test_for_selected_VPN_servers {
            get {
                return ResourceManager.GetString("Run_test_for_selected_VPN_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run test for this VPN server.
        /// </summary>
        public static string Run_test_for_this_VPN_server {
            get {
                return ResourceManager.GetString("Run_test_for_this_VPN_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running job found. They will be aborted or press &quot;Cancel&quot; to exit.
        /// </summary>
        public static string Running_job_found__They_will_be_aborted_or_press__Cancel__to_exit {
            get {
                return ResourceManager.GetString("Running_job_found__They_will_be_aborted_or_press__Cancel__to_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Address: .
        /// </summary>
        public static string Server_IP_Address__ {
            get {
                return ResourceManager.GetString("Server_IP_Address__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default VPN connection .
        /// </summary>
        public static string Set_as_default_VPN_connection_ {
            get {
                return ResourceManager.GetString("Set_as_default_VPN_connection_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show active VPN connection info.
        /// </summary>
        public static string Show_active_VPN_connection_info {
            get {
                return ResourceManager.GetString("Show_active_VPN_connection_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show created VPN entries info.
        /// </summary>
        public static string Show_created_VPN_entries_info {
            get {
                return ResourceManager.GetString("Show_created_VPN_entries_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for VPN server.
        /// </summary>
        public static string Test_for_VPN_server {
            get {
                return ResourceManager.GetString("Test_for_VPN_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Phonebook path: .
        /// </summary>
        public static string User_Phonebook_path__ {
            get {
                return ResourceManager.GetString("User_Phonebook_path__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN.
        /// </summary>
        public static string VPN {
            get {
                return ResourceManager.GetString("VPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN dialer failed: .
        /// </summary>
        public static string VPN_dialer_failed__ {
            get {
                return ResourceManager.GetString("VPN_dialer_failed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN disconnected.
        /// </summary>
        public static string VPN_disconnected {
            get {
                return ResourceManager.GetString("VPN_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon vpn_off {
            get {
                object obj = ResourceManager.GetObject("vpn_off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon vpn_on {
            get {
                object obj = ResourceManager.GetObject("vpn_on", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN selector.
        /// </summary>
        public static string VPN_selector {
            get {
                return ResourceManager.GetString("VPN_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN server by default.
        /// </summary>
        public static string VPN_server_by_default {
            get {
                return ResourceManager.GetString("VPN_server_by_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning_ {
            get {
                return ResourceManager.GetString("Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrning.
        /// </summary>
        public static string Warrning {
            get {
                return ResourceManager.GetString("Warrning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
