//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionext {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAccountLibRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAccountLibRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionext.WebAccountLibRes", typeof(WebAccountLibRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /persistent common cache/.
        /// </summary>
        public static string @__common_cache {
            get {
                return ResourceManager.GetString("__common_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /in memory cache/.
        /// </summary>
        public static string @__private_in_memory_cache_ {
            get {
                return ResourceManager.GetString("__private_in_memory_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /persistent entity cache/.
        /// </summary>
        public static string @__private_persistent_cache_ {
            get {
                return ResourceManager.GetString("__private_persistent_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /persistent cache (cleared)/.
        /// </summary>
        public static string @__private_persistent_cache__cleared__ {
            get {
                return ResourceManager.GetString("__private_persistent_cache__cleared__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required VPN connection. It is filled in if for this entity it is recommended to go online through a specific VPN connection.
        /// </summary>
        public static string AllowedVPNServer {
            get {
                return ResourceManager.GetString("AllowedVPNServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesomium.
        /// </summary>
        public static string Awesomium {
            get {
                return ResourceManager.GetString("Awesomium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web account.
        /// </summary>
        public static string BaseWebAccount {
            get {
                return ResourceManager.GetString("BaseWebAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional and old bank accounts.
        /// </summary>
        public static string BaseWebAccount_AddJMoneyBankAcc {
            get {
                return ResourceManager.GetString("BaseWebAccount_AddJMoneyBankAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Password.
        /// </summary>
        public static string BaseWebAccount_AppPassword {
            get {
                return ResourceManager.GetString("BaseWebAccount_AppPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Answer.
        /// </summary>
        public static string BaseWebAccount_ControlAns {
            get {
                return ResourceManager.GetString("BaseWebAccount_ControlAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Question.
        /// </summary>
        public static string BaseWebAccount_ControlQ {
            get {
                return ResourceManager.GetString("BaseWebAccount_ControlQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance with oAuth.
        /// </summary>
        public static string BaseWebAccount_EntranceByOAuth {
            get {
                return ResourceManager.GetString("BaseWebAccount_EntranceByOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign of &quot;expired&quot;. If the account is considered expired (due to lack of payment or lack of activity..
        /// </summary>
        public static string BaseWebAccount_Expired {
            get {
                return ResourceManager.GetString("BaseWebAccount_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration validity period. The period after which the account is expired (due to lack of payment or lack of activity)..
        /// </summary>
        public static string BaseWebAccount_ExpiredPeriod {
            get {
                return ResourceManager.GetString("BaseWebAccount_ExpiredPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string BaseWebAccount_FullName {
            get {
                return ResourceManager.GetString("BaseWebAccount_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string BaseWebAccount_Info {
            get {
                return ResourceManager.GetString("BaseWebAccount_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string BaseWebAccount_IsArchived {
            get {
                return ResourceManager.GetString("BaseWebAccount_IsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string BaseWebAccount_JAccountId {
            get {
                return ResourceManager.GetString("BaseWebAccount_JAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string BaseWebAccount_JActor {
            get {
                return ResourceManager.GetString("BaseWebAccount_JActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail confirmation address.
        /// </summary>
        public static string BaseWebAccount_JMailAccount {
            get {
                return ResourceManager.GetString("BaseWebAccount_JMailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account.
        /// </summary>
        public static string BaseWebAccount_JMoneyBankAcc {
            get {
                return ResourceManager.GetString("BaseWebAccount_JMoneyBankAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation phone.
        /// </summary>
        public static string BaseWebAccount_JPhoneNumber {
            get {
                return ResourceManager.GetString("BaseWebAccount_JPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string BaseWebAccount_JWeb {
            get {
                return ResourceManager.GetString("BaseWebAccount_JWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of the last confirmation of activity. Used to control the &quot;expiration&quot; of the account.
        /// </summary>
        public static string BaseWebAccount_LastRenewDate {
            get {
                return ResourceManager.GetString("BaseWebAccount_LastRenewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BaseWebAccount_Login {
            get {
                return ResourceManager.GetString("BaseWebAccount_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth account. Third-party account that must be used to access this resource (via OAuth protocol).
        /// </summary>
        public static string BaseWebAccount_OAuthWebAccount {
            get {
                return ResourceManager.GetString("BaseWebAccount_OAuthWebAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string BaseWebAccount_Password {
            get {
                return ResourceManager.GetString("BaseWebAccount_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string BaseWebAccount_ShortName {
            get {
                return ResourceManager.GetString("BaseWebAccount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium Embedded.
        /// </summary>
        public static string Chromium_Embedded {
            get {
                return ResourceManager.GetString("Chromium_Embedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear browser cache for entity.
        /// </summary>
        public static string Clear_browser_cache_for_entity {
            get {
                return ResourceManager.GetString("Clear_browser_cache_for_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear browser cache for entity actor.
        /// </summary>
        public static string Clear_browser_cache_for_entity_actor {
            get {
                return ResourceManager.GetString("Clear_browser_cache_for_entity_actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear common browser cache.
        /// </summary>
        public static string Clear_common_browser_cache {
            get {
                return ResourceManager.GetString("Clear_common_browser_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;OK&quot; to ignore the warning and continue. Click &quot;Cancel&quot; to cancel.
        /// </summary>
        public static string Click_OK_to_ignore_the_warning_and_continue_Click_Cancel_to_cancel {
            get {
                return ResourceManager.GetString("Click_OK_to_ignore_the_warning_and_continue_Click_Cancel_to_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; to connect to the desired VPN server. Click &quot;No&quot; to ignore the warning and continue. Click &quot;Cancel&quot; to cancel..
        /// </summary>
        public static string Click_Yes_to_connect_to_the_desired_VPN_server {
            get {
                return ResourceManager.GetString("Click_Yes_to_connect_to_the_desired_VPN_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy login to clipboard.
        /// </summary>
        public static string Copy_login_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_login_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password to clipboard.
        /// </summary>
        public static string Copy_password_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_password_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current VPN connection is not established..
        /// </summary>
        public static string Current_VPN_connection_is_not_established {
            get {
                return ResourceManager.GetString("Current_VPN_connection_is_not_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this entity, you need access to the Internet through a specific VPN connection..
        /// </summary>
        public static string For_this_entity_you_need_access_to_the_Internet_through_a_specific_VPN {
            get {
                return ResourceManager.GetString("For_this_entity_you_need_access_to_the_Internet_through_a_specific_VPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_actor {
            get {
                object obj = ResourceManager.GetObject("fr_actor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_mailaccount {
            get {
                object obj = ResourceManager.GetObject("fr_mailaccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_web {
            get {
                object obj = ResourceManager.GetObject("fr_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_webaccount {
            get {
                object obj = ResourceManager.GetObject("fr_webaccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_webaccount1 {
            get {
                object obj = ResourceManager.GetObject("fr_webaccount1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_webfolder {
            get {
                object obj = ResourceManager.GetObject("fr_webfolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new password.
        /// </summary>
        public static string Generate_new_password {
            get {
                return ResourceManager.GetString("Generate_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in default external application.
        /// </summary>
        public static string In_default_external_application {
            get {
                return ResourceManager.GetString("In_default_external_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string JPhoneNumber_Attachments {
            get {
                return ResourceManager.GetString("JPhoneNumber_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string JPhoneNumber_Balance {
            get {
                return ResourceManager.GetString("JPhoneNumber_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string JPhoneNumber_Country {
            get {
                return ResourceManager.GetString("JPhoneNumber_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string JPhoneNumber_Info {
            get {
                return ResourceManager.GetString("JPhoneNumber_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string JPhoneNumber_IsArchived {
            get {
                return ResourceManager.GetString("JPhoneNumber_IsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string JPhoneNumber_JActor {
            get {
                return ResourceManager.GetString("JPhoneNumber_JActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile operator.
        /// </summary>
        public static string JPhoneNumber_JMobileOperator {
            get {
                return ResourceManager.GetString("JPhoneNumber_JMobileOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string JPhoneNumber_JPhoneNumberId {
            get {
                return ResourceManager.GetString("JPhoneNumber_JPhoneNumberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string JPhoneNumber_Login {
            get {
                return ResourceManager.GetString("JPhoneNumber_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string JPhoneNumber_Number {
            get {
                return ResourceManager.GetString("JPhoneNumber_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string JPhoneNumber_Owner {
            get {
                return ResourceManager.GetString("JPhoneNumber_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string JPhoneNumber_Password {
            get {
                return ResourceManager.GetString("JPhoneNumber_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение.
        /// </summary>
        public static string JPhoneNumber_Purpose {
            get {
                return ResourceManager.GetString("JPhoneNumber_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebEntryInfo.
        /// </summary>
        public static string JPhoneNumber_WebEntryInfo {
            get {
                return ResourceManager.GetString("JPhoneNumber_WebEntryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string JWeb_Info {
            get {
                return ResourceManager.GetString("JWeb_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string JWeb_IsArchived {
            get {
                return ResourceManager.GetString("JWeb_IsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string JWeb_JWeb {
            get {
                return ResourceManager.GetString("JWeb_JWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web category.
        /// </summary>
        public static string JWeb_JWebCategory {
            get {
                return ResourceManager.GetString("JWeb_JWebCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string JWeb_JWebId {
            get {
                return ResourceManager.GetString("JWeb_JWebId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JWeb_Name {
            get {
                return ResourceManager.GetString("JWeb_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier.
        /// </summary>
        public static string JWeb_SrcId {
            get {
                return ResourceManager.GetString("JWeb_SrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string JWeb_Url {
            get {
                return ResourceManager.GetString("JWeb_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web category.
        /// </summary>
        public static string JWebCategory_JWebCategory {
            get {
                return ResourceManager.GetString("JWebCategory_JWebCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string JWebCategory_JWebCategoryId {
            get {
                return ResourceManager.GetString("JWebCategory_JWebCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JWebCategory_Name {
            get {
                return ResourceManager.GetString("JWebCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent web category.
        /// </summary>
        public static string JWebCategory_Parent {
            get {
                return ResourceManager.GetString("JWebCategory_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier.
        /// </summary>
        public static string JWebCategory_SrcId {
            get {
                return ResourceManager.GetString("JWebCategory_SrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail and messangers.
        /// </summary>
        public static string Mail_and_messangers {
            get {
                return ResourceManager.GetString("Mail_and_messangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Word.
        /// </summary>
        public static string MS_Word {
            get {
                return ResourceManager.GetString("MS_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Open_folder {
            get {
                return ResourceManager.GetString("Open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in.
        /// </summary>
        public static string Open_in {
            get {
                return ResourceManager.GetString("Open_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in .
        /// </summary>
        public static string Open_in_ {
            get {
                return ResourceManager.GetString("Open_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Chrome.
        /// </summary>
        public static string Open_in_Chrome {
            get {
                return ResourceManager.GetString("Open_in_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in embedded browser.
        /// </summary>
        public static string Open_in_embedded_browser {
            get {
                return ResourceManager.GetString("Open_in_embedded_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in external.
        /// </summary>
        public static string Open_in_external {
            get {
                return ResourceManager.GetString("Open_in_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in external Chrome.
        /// </summary>
        public static string Open_in_external_Chrome {
            get {
                return ResourceManager.GetString("Open_in_external_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in FireFox.
        /// </summary>
        public static string Open_in_FireFox {
            get {
                return ResourceManager.GetString("Open_in_FireFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in IE (deprecated).
        /// </summary>
        public static string Open_in_IE__deprecated_ {
            get {
                return ResourceManager.GetString("Open_in_IE__deprecated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in IE (KeeForm) and try to autocomplate web form: .
        /// </summary>
        public static string Open_in_IE__KeeForm__and_try_to_autocomplate_web_form__ {
            get {
                return ResourceManager.GetString("Open_in_IE__KeeForm__and_try_to_autocomplate_web_form__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Microsoft Edge.
        /// </summary>
        public static string Open_in_Microsoft_Edge {
            get {
                return ResourceManager.GetString("Open_in_Microsoft_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Opera.
        /// </summary>
        public static string Open_in_Opera {
            get {
                return ResourceManager.GetString("Open_in_Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Safary.
        /// </summary>
        public static string Open_in_Safary {
            get {
                return ResourceManager.GetString("Open_in_Safary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portable.
        /// </summary>
        public static string Portable {
            get {
                return ResourceManager.GetString("Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private mode.
        /// </summary>
        public static string private_mode {
            get {
                return ResourceManager.GetString("private_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple editor.
        /// </summary>
        public static string Simple_editor {
            get {
                return ResourceManager.GetString("Simple_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current VPN connection does not match the one specified for this entity..
        /// </summary>
        public static string The_current_VPN_connection_does_not_match {
            get {
                return ResourceManager.GetString("The_current_VPN_connection_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This VPN connection has not been established and was not found among the possible connections..
        /// </summary>
        public static string This_VPN_connection_has_not_been_established {
            get {
                return ResourceManager.GetString("This_VPN_connection_has_not_been_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to clipboard.
        /// </summary>
        public static string to_clipboard {
            get {
                return ResourceManager.GetString("to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web (tree).
        /// </summary>
        public static string Web__tree_ {
            get {
                return ResourceManager.GetString("Web__tree_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web accounts management.
        /// </summary>
        public static string Web_accounts_management {
            get {
                return ResourceManager.GetString("Web_accounts_management", resourceCulture);
            }
        }
    }
}
