//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionext {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAccountLibRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAccountLibRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionext.WebAccountLibRes", typeof(WebAccountLibRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /private in memory cache/.
        /// </summary>
        public static string @__private_in_memory_cache_ {
            get {
                return ResourceManager.GetString("__private_in_memory_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /private persistent cache/.
        /// </summary>
        public static string @__private_persistent_cache_ {
            get {
                return ResourceManager.GetString("__private_persistent_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  /private persistent cache (cleared)/.
        /// </summary>
        public static string @__private_persistent_cache__cleared__ {
            get {
                return ResourceManager.GetString("__private_persistent_cache__cleared__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesomium.
        /// </summary>
        public static string Awesomium {
            get {
                return ResourceManager.GetString("Awesomium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web account.
        /// </summary>
        public static string BaseWebAccount {
            get {
                return ResourceManager.GetString("BaseWebAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string BaseWebAccount_FullName {
            get {
                return ResourceManager.GetString("BaseWebAccount_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string BaseWebAccount_Info {
            get {
                return ResourceManager.GetString("BaseWebAccount_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string BaseWebAccount_IsArchive {
            get {
                return ResourceManager.GetString("BaseWebAccount_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string BaseWebAccount_JAccountId {
            get {
                return ResourceManager.GetString("BaseWebAccount_JAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string BaseWebAccount_JWeb {
            get {
                return ResourceManager.GetString("BaseWebAccount_JWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string BaseWebAccount_Login {
            get {
                return ResourceManager.GetString("BaseWebAccount_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string BaseWebAccount_Password {
            get {
                return ResourceManager.GetString("BaseWebAccount_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string BaseWebAccount_ShortName {
            get {
                return ResourceManager.GetString("BaseWebAccount_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium Embedded.
        /// </summary>
        public static string Chromium_Embedded {
            get {
                return ResourceManager.GetString("Chromium_Embedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy login to clipboard.
        /// </summary>
        public static string Copy_login_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_login_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy password to clipboard.
        /// </summary>
        public static string Copy_password_to_clipboard {
            get {
                return ResourceManager.GetString("Copy_password_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_web {
            get {
                object obj = ResourceManager.GetObject("fr_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_webaccount {
            get {
                object obj = ResourceManager.GetObject("fr_webaccount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fr_webfolder {
            get {
                object obj = ResourceManager.GetObject("fr_webfolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new password.
        /// </summary>
        public static string Generate_new_password {
            get {
                return ResourceManager.GetString("Generate_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in default external application.
        /// </summary>
        public static string In_default_external_application {
            get {
                return ResourceManager.GetString("In_default_external_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string JWeb_Info {
            get {
                return ResourceManager.GetString("JWeb_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string JWeb_IsArchive {
            get {
                return ResourceManager.GetString("JWeb_IsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string JWeb_JWeb {
            get {
                return ResourceManager.GetString("JWeb_JWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web category.
        /// </summary>
        public static string JWeb_JWebCategory {
            get {
                return ResourceManager.GetString("JWeb_JWebCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string JWeb_JWebId {
            get {
                return ResourceManager.GetString("JWeb_JWebId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JWeb_Name {
            get {
                return ResourceManager.GetString("JWeb_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier.
        /// </summary>
        public static string JWeb_SrcId {
            get {
                return ResourceManager.GetString("JWeb_SrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string JWeb_Url {
            get {
                return ResourceManager.GetString("JWeb_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web category.
        /// </summary>
        public static string JWebCategory_JWebCategory {
            get {
                return ResourceManager.GetString("JWebCategory_JWebCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string JWebCategory_JWebCategoryId {
            get {
                return ResourceManager.GetString("JWebCategory_JWebCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JWebCategory_Name {
            get {
                return ResourceManager.GetString("JWebCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent web category.
        /// </summary>
        public static string JWebCategory_Parent {
            get {
                return ResourceManager.GetString("JWebCategory_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source identifier.
        /// </summary>
        public static string JWebCategory_SrcId {
            get {
                return ResourceManager.GetString("JWebCategory_SrcId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Word.
        /// </summary>
        public static string MS_Word {
            get {
                return ResourceManager.GetString("MS_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string Open_folder {
            get {
                return ResourceManager.GetString("Open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in.
        /// </summary>
        public static string Open_in {
            get {
                return ResourceManager.GetString("Open_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in .
        /// </summary>
        public static string Open_in_ {
            get {
                return ResourceManager.GetString("Open_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Chrome.
        /// </summary>
        public static string Open_in_Chrome {
            get {
                return ResourceManager.GetString("Open_in_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in embedded browser.
        /// </summary>
        public static string Open_in_embedded_browser {
            get {
                return ResourceManager.GetString("Open_in_embedded_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in external.
        /// </summary>
        public static string Open_in_external {
            get {
                return ResourceManager.GetString("Open_in_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in external Chrome.
        /// </summary>
        public static string Open_in_external_Chrome {
            get {
                return ResourceManager.GetString("Open_in_external_Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in FireFox.
        /// </summary>
        public static string Open_in_FireFox {
            get {
                return ResourceManager.GetString("Open_in_FireFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in IE (deprecated).
        /// </summary>
        public static string Open_in_IE__deprecated_ {
            get {
                return ResourceManager.GetString("Open_in_IE__deprecated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in IE (KeeForm) and try to autocomplate web form: .
        /// </summary>
        public static string Open_in_IE__KeeForm__and_try_to_autocomplate_web_form__ {
            get {
                return ResourceManager.GetString("Open_in_IE__KeeForm__and_try_to_autocomplate_web_form__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Microsoft Edge.
        /// </summary>
        public static string Open_in_Microsoft_Edge {
            get {
                return ResourceManager.GetString("Open_in_Microsoft_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Opera.
        /// </summary>
        public static string Open_in_Opera {
            get {
                return ResourceManager.GetString("Open_in_Opera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Safary.
        /// </summary>
        public static string Open_in_Safary {
            get {
                return ResourceManager.GetString("Open_in_Safary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portable.
        /// </summary>
        public static string Portable {
            get {
                return ResourceManager.GetString("Portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private mode.
        /// </summary>
        public static string private_mode {
            get {
                return ResourceManager.GetString("private_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple editor.
        /// </summary>
        public static string Simple_editor {
            get {
                return ResourceManager.GetString("Simple_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to clipboard.
        /// </summary>
        public static string to_clipboard {
            get {
                return ResourceManager.GetString("to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate new password press &quot;Yes&quot; .
        /// </summary>
        public static string To_generate_new_password_press__Yes__ {
            get {
                return ResourceManager.GetString("To_generate_new_password_press__Yes__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web (tree).
        /// </summary>
        public static string Web__tree_ {
            get {
                return ResourceManager.GetString("Web__tree_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web accounts management.
        /// </summary>
        public static string Web_accounts_management {
            get {
                return ResourceManager.GetString("Web_accounts_management", resourceCulture);
            }
        }
    }
}
